### ISSUE TITLE
Высвечивать текущий контекст

### ISSUE THREAD

**Issue by pavelvasev** [Mitricho/DocsiteMuse#1]
У Музы довольно длинный список опций. Когда по нему листаешь быстро теряешь контекст, где находишься. Предложение - при прокрутке высвечивать наверху текущий контекст название, "общие настройки", "панель навигации", "обложка меню" и т.д.

**Comment by pavelvasev** [comment]
Может быть, высвечивать его подсвечивая не название а иконку в вертикальном меню иконок, см #2

**Comment by Mitricho** [comment]
Совершена попытка высвечивать наверху текущий контекст название. Версия 1.14

**Comment by pavelvasev** [comment]
Вижу! Круто! Спасибо!!!
