### ISSUE TITLE
Указать шрифты

### ISSUE THREAD

**Issue by pavelvasev** [Mitricho/DocsiteMuse#3]
В окне "указать шрифты" - хотелось бы видеть как будут выглядеть шрифты. А то непонятка, угадайка. Особенно если кто с ними не знаком.

**Comment by Mitricho** [comment]
Это нереально с веб-шрифтами. Для превью надо запрашивать все шрифты с сервера. Можно предварительно нагенерить, но неясно как

**Comment by Mitricho** [comment]
А мир таки не без добрых людей ) https://github.com/getstencil/GoogleWebFonts-FontFamilyPreviewImages
Со временем сделаю.

**Comment by Mitricho** [comment]
Превью шрифта показывается теперь. Хорошая мысль, спасибо!

**Comment by Mitricho** [comment]
Готово. Зкрываю.
