### ISSUE TITLE
Подчеркивание ссылок в панели навигации

### ISSUE THREAD

**Issue by pavelvasev** [Mitricho/DocsiteMuse#4]
Панель навигации (самое верхнее меню) и там ссылки. У них есть опция жирный, курсив. Предложение добавить еще опцию подчеркивания. 
Мотивация-  не будучи выделенны как кнопочки, не очевидны вообще что являются ссылками/менюшками.. Почеркивание вроде как шаг в эту сторону без спец-затрат.

**Comment by Mitricho** [comment]
Готово.

**Comment by pavelvasev** [comment]
Посмотрели, супер!!!
