### ISSUE TITLE
Отступы колонок

### ISSUE THREAD

**Issue by pavelvasev** [Mitricho/DocsiteMuse#5]
Можно ли как-то регулировать отступ колонок от боков? (а также и внутри). Посмотрел сейчас навешивается класс p-4, а там еще ведь и p-3 в стилях есть и т.п. p4 дает отступ 2.25rem, хотелось бы например 1.5 или 1 даже уметь выбрать... Или это дизайнерское решение и точка? (жалко очень пр-во между левой колонкой и контентом, прям перебор кажется...).

**Comment by pavelvasev** [comment]
![Screenshot from 2021-11-01 21-03-44](https://user-images.githubusercontent.com/159179/139703948-bd35e6b1-6fdd-4fc2-9d18-c60aaa6cc254.png)

**Comment by Mitricho** [comment]
Добавил настройку этого всего в группу Контент->Основное.

**Comment by pavelvasev** [comment]
Супер! То что надо!
