### ISSUE TITLE
След слогана на баннере

### ISSUE THREAD

**Issue by pavelvasev** [Mitricho/DocsiteMuse#8]
Если у сайта не указан слоган, то все-равно виден след обводки слогана на логотипе.
Пример - в центре баннера http://www.rosselchozcentr-saratov.ru/?7629

**Comment by Mitricho** [comment]
Можешь принтскрин загрузить? У меня сходу ничего не видно такого.

**Comment by pavelvasev** [comment]
5 пикс выше слова ИМИДЖ, зеленая полоска. Эта картинка удачно скрывает, но на других будет хуже.

![Screenshot from 2021-11-02 09-20-31](https://user-images.githubusercontent.com/159179/139786425-5af19a87-064f-4336-a5fa-514ebdd47656.png)

**Comment by Mitricho** [comment]
Это пятно можно убрать в Обложка\Текст обложки\Подложка - на прозрачный. Плюс в версии 1.16 span слогана прячется, если пустой

**Comment by pavelvasev** [comment]
Хорошо что сам прячется, спасибо!
